added two functions and tests
algorithms-club/algorithms-havrylova pull request #1
Opened 2017-03-31 18:53 UTC by mhavrylova

Please review my solving of two tasks.

2017-04-05 18:55 UTC, PavelMelnyk commented
Description very general
you should describe in pull request what functionality you added
mention what it should solve
### Example
Added methods for solving tasks
- watermelon
- nextYearFind
- tests for methods

2017-04-05 19:25 UTC, pavlom0x requested changes
Please fix indentation

2017-04-05 19:25 UTC, PavelMelnyk commented on entry-test/nextYearFind.js
> +
why do wi need extra space?

2017-04-05 19:25 UTC, PavelMelnyk commented on entry-test/nextYearFind.js
> +        }
You have indentation issue, it's bad practice write code like that

2017-04-05 19:25 UTC, PavelMelnyk commented on entry-test/nextYearFind.js
> +	if ( year > 9000 || year < 1000 || year === null || year === undefined || isNaN( year ) ) {
if you check `isNaN` 
this not needed `year === null || year === undefined ||`

2017-04-05 19:25 UTC, PavelMelnyk commented on entry-test/nextYearFind.js
> +  	let yearN = year.toString();
where you use this variable?

2017-04-05 19:25 UTC, PavelMelnyk commented on entry-test/watermelon.js
> +if ( weight < 1 || weight > 100 || weight === null || weight === undefined || isNaN( weight ) ) {
if you check isNaN
this not needed year === null || year === undefined ||

2017-04-05 19:25 UTC, PavelMelnyk commented on entry-test/nextYearFind.js
> +module.exports = nextYearFind;
It's good if in end of file you write empty line
in each file

2017-04-06 19:09 UTC, mhavrylova commented on entry-test/nextYearFind.js
> +
fixed

2017-04-17 21:39 UTC, pavlom0x approved these changes
well done

2017-05-03 19:17 UTC, PavelMelnyk commented
merge it if it ready

2017-05-04 18:57 UTC, PavelMelnyk commented
please merge it if you done

2017-05-04 19:44 UTC, merged